### ISSUE TITLE
Make sure frontend code doesn't need to depend on anchor

### ISSUE THREAD

**Issue by crypto-vincent** [magicblock-labs/bolt#61]
**Is your feature request related to a problem? Please describe.**

When building the frontend of a BOLT application the users ends up having to have the whole of anchor as a direct dependency to parse the IDLs of the components/systems

**Describe the solution you'd like**

Ideally we would provide a way to automatically serialize/deserialize data without having the user need to import direct anchor APIs

**Comment by iamnamananand996** [comment]
Hi @GabrielePicco, @crypto-vincent.

Rather than creating the custom `serialize/deserialize`, I would suggest to re-export the `@coral-xyz/anchor` from our `@magicblock-labs/bolt-sdk` because, their we have already installed it. 
In that way we does not need frontend to again add  `@coral-xyz/anchor`, just add `@magicblock-labs/bolt-sdk` and consume all API's.

## Example

### Re-export example

```typescript

// Import necessary modules from @coral-xyz/anchor
import * as anchor from "@coral-xyz/anchor";
export { anchor };

// Optionally, export specific components from @coral-xyz/anchor if needed
export {
  Provider,
  Program,
  Wallet,
  web3,
  workspace,
  BN, // If you want to re-export BN from anchor
} from "@coral-xyz/anchor";
```

### Consuming through our SDK

```typescript

import { anchor } from "@magicblock-labs/bolt-sdk";

// Use anchor's APIs
const provider = new anchor.Provider(...);
const program = new anchor.Program(...);

```

----------------------------------------------------------------

> **Let me know if you like the solution, I can make this changes**
